name: Test Runner
on: [push]

jobs:
  run-test:
    runs-on: self-hosted
    steps:
      - name: Message de test
        run: echo "Job exécuté depuis le runner auto-hébergé"
      - name: Installer tree
        run: sudo apt update && sudo apt install -y tree

      - name: Créer un fichier
        run: |
          mkdir output
          echo "Ceci est un fichier généré" > output/test.txt

      - name: Lister les fichiers
        run: tree .

      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: fichier-genere
          path: output/test.txt
