name: Test Runner GitHub

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest  # Utilise un runner hébergé GitHub

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Étape de test
        run: |
          echo "✅ Test réussi sur un runner hébergé"
          mkdir -p test-output
          echo "Contenu du test" > test-output/output.txt

      - name: Upload du résultat
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: test-output/output.txt
