name: Test Runner Windows

on: [push]

jobs:
  run-test:
    runs-on: self-hosted  # Ton runner Windows auto-hébergé

    steps:
      - name: Message de test
        run: echo "Job exécuté depuis le runner Windows auto-hébergé"

      - name: Créer un fichier
        run: |
          mkdir output
          echo Ceci est un fichier généré > output\test.txt

      - name: Lister les fichiers
        run: dir

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: fichier-genere
          path: output\test.txt
